# Generated by Django 5.0.3 on 2024-05-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_update_producto_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='existencias',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
